name:
  cgraph_mclcl1
channels:
  - conda-forge
  - anaconda
  - pytorch
  - ostrokach-forge
  - pyg
dependencies:
  - python=3.7
  - cudatoolkit=10.1
  - pytorch=1.4.0
#  -  torchvision==0.5.0 -f https://download.pytorch.org/whl/cu101/torchvision-0.5.0-cp37-cp37m-linux_x86_64.whl
#  -  pip install -f https://download.pytorch.org/whl/cu101/torchvision-0.5.0-cp37-cp37m-linux_x86_64.whl torchvision==0.5.0
#  mamba env install torchvision=0.5.0 -c pytorch
# conda install pytorch==1.4.0 torchvision==0.5.0 cudatoolkit=10.1 -c pytorch -c conda-forge
  - numpy=1.19.0
  - pillow=7.2.0
  - six=1.15.0
  - pip: # download these packages manually
    - torch-scatter -f https://data.pyg.org/whl/torch-1.4.0%2Bcu101/torch_scatter-2.0.4-cp37-cp37m-linux_x86_64.whl
    - torch-sparse -f https://data.pyg.org/whl/torch-1.4.0%2Bcu101/torch_sparse-0.6.1-cp37-cp37m-linux_x86_64.whl
    - torch-cluster -f https://data.pyg.org/whl/torch-1.4.0/torch_cluster-1.5.2%2Bcu101-cp37-cp37m-linux_x86_64.whl
    - torch-spline-conv -f https://data.pyg.org/whl/torch-1.4.0%2Bcu101/torch_spline_conv-1.2.0-cp37-cp37m-linux_x86_64.whl
    - torch-geometric==1.0.3 -f https://pytorch-geometric.com/whl/torch-1.4.0%2Bcu101.html

# pip install -f https://data.pyg.org/whl/torch-1.4.0%2Bcu101/torch_spline_conv-1.2.0-cp37-cp37m-linux_x86_64.whl torch-spline-conv
